MAIN = streaming3
SRCS = streaming3.c

INCLUDES = -I/usr/include/SDL2

LIBS = -lSDL2 -lSDL2_image -lpthread

OBJS =$(SRCS:.c=.o)

CC = gcc

CFLAGS = -Wall -g -O3


$(MAIN): $(OBJ)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@


clean:
	$(RM) *.o *~ $(MAIN)

depend: $(SRCS)
	makedepend $(INCLUDES) $^
# DO NOT DELETE

streaming3.o: /usr/include/stdio.h /usr/include/stdlib.h
streaming3.o: /usr/include/search.h /usr/include/features.h
streaming3.o: /usr/include/stdc-predef.h /usr/include/assert.h
streaming3.o: /usr/include/SDL2/SDL.h /usr/include/SDL2/SDL_main.h
streaming3.o: /usr/include/SDL2/SDL_stdinc.h /usr/include/SDL2/SDL_config.h
streaming3.o: /usr/include/SDL2/begin_code.h /usr/include/SDL2/close_code.h
streaming3.o: /usr/include/SDL2/SDL_assert.h /usr/include/SDL2/SDL_atomic.h
streaming3.o: /usr/include/SDL2/SDL_platform.h /usr/include/SDL2/SDL_audio.h
streaming3.o: /usr/include/SDL2/SDL_error.h /usr/include/SDL2/SDL_endian.h
streaming3.o: /usr/include/SDL2/SDL_mutex.h /usr/include/SDL2/SDL_thread.h
streaming3.o: /usr/include/SDL2/SDL_rwops.h /usr/include/SDL2/SDL_clipboard.h
streaming3.o: /usr/include/SDL2/SDL_cpuinfo.h /usr/include/SDL2/SDL_events.h
streaming3.o: /usr/include/SDL2/SDL_video.h /usr/include/SDL2/SDL_pixels.h
streaming3.o: /usr/include/SDL2/SDL_rect.h /usr/include/SDL2/SDL_surface.h
streaming3.o: /usr/include/SDL2/SDL_blendmode.h
streaming3.o: /usr/include/SDL2/SDL_keyboard.h
streaming3.o: /usr/include/SDL2/SDL_keycode.h
streaming3.o: /usr/include/SDL2/SDL_scancode.h /usr/include/SDL2/SDL_mouse.h
streaming3.o: /usr/include/SDL2/SDL_joystick.h
streaming3.o: /usr/include/SDL2/SDL_gamecontroller.h
streaming3.o: /usr/include/SDL2/SDL_quit.h /usr/include/SDL2/SDL_gesture.h
streaming3.o: /usr/include/SDL2/SDL_touch.h
streaming3.o: /usr/include/SDL2/SDL_filesystem.h
streaming3.o: /usr/include/SDL2/SDL_haptic.h /usr/include/SDL2/SDL_hints.h
streaming3.o: /usr/include/SDL2/SDL_loadso.h /usr/include/SDL2/SDL_log.h
streaming3.o: /usr/include/SDL2/SDL_messagebox.h
streaming3.o: /usr/include/SDL2/SDL_power.h /usr/include/SDL2/SDL_render.h
streaming3.o: /usr/include/SDL2/SDL_sensor.h /usr/include/SDL2/SDL_shape.h
streaming3.o: /usr/include/SDL2/SDL_system.h /usr/include/SDL2/SDL_timer.h
streaming3.o: /usr/include/SDL2/SDL_version.h /usr/include/SDL2/SDL_image.h
